// Generated by CoffeeScript 1.3.2
(function() {

  module.exports = function(url) {
    if (url == null) {
      url = '/jquery.js';
    }
    return function(req, res, next) {
      if (req.url === url) {
        return res.sendfile(__dirname + '/vendor/jquery-1.8.3.min.js');
      } else {
        return next();
      }
    };
  };

}).call(this);
